const product=[
    {
        id:1,
        name:"T-shirt",
        category:"men",
        price:500,
    },
    {
        id:2,
        name:"shirt",
        category:"men",
        price:700,
    },
    {
        id:3,
        name:"shoes",
        category:"kids",
        price:1000,
    },
    {
        id:4,
        name:"shocks",
        category:"men",
        price:100,
    },
    {
        id:5,
        name:"jean",
        category:"women",
        price:1100,
    },
    {
        id:6,
        name:"jogger",
        category:"women",
        price:500,
    },
    {
        id:7,
        name:"T-shirt",
        category:"kids",
        price:500,
    },
    {
        id:8,
        name:"belt",
        category:"men",
        price:540,
    },
    {
        id:9,
        name:"sunglasses",
        category:"men",
        price:5030,
    },
    {
        id:10,
        name:"eye lens",
        category:"men",
        price:500,
    },
    {
        id:11,
        name:"ring",
        category:"men",
        price:1500,
    },
    {
        id:12,
        name:"fog",
        category:"men",
        price:1500,
    },
    {
        id:13,
        name:"hair spray",
        category:"men",
        price:500
    },
    {
        id:14,
        name:"bracelet",
        category:"men",
        price:300,
    },
    {
        id:15,
        name:"cap",
        category:"kids",
        price:500,
    },
]

export default product;