const studentList=[
    {
        id:1,
        name:"shubham",
        course:"mean",
    },
    {
        id:2,
        name:"kundam",
        course:"mern",
    },
    {
        id:3,
        name:"sahil",
        course:"php",
    },
    {
        id:4,
        name:"sonam",
        course:"angular",
    },
    {
        id:11,
        name:"komal",
        course:"mern",
    },
    {
        id:5,
        name:"shubham",
        course:"mean",
    },
    {
        id:6,
        name:"arun",
        course:"mean",
    },
    {
        id:7,
        name:"sanjeev",
        course:"mean",
    },
    {
        id:8,
        name:"priyanka",
        course:"mean",
    },
    {
        id:9,
        name:"mohan",
        course:"mean",
    },
    {
        id:10,
        name:"vikram",
        course:"mean",
    },
];

export default studentList;